<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><TargetFramework>net8.0</TargetFramework></PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../WorkFlowWidget.Core/WorkFlowWidget.Core.csproj" />
    <PackageReference Include="Microsoft.Identity.Client" Version="4.90.1" />
    <PackageReference Include="Microsoft.Identity.Client.Broker" Version="4.90.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="8.0.31" />
  </ItemGroup>
</Project>
