<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
  </PropertyGroup>
  <ItemGroup>
    <None Update="appsettings.json" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
    <ProjectReference Include="../WorkFlowWidget.Core/WorkFlowWidget.Core.csproj" />
    <ProjectReference Include="../WorkFlowWidget.Infrastructure/WorkFlowWidget.Infrastructure.csproj" />
  </ItemGroup>
</Project>
